# Generated by Django 2.1.7 on 2021-11-24 00:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211123_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 11, 23, 21, 57, 37, 307645)),
        ),
    ]
